theme: minima

title: Tmorales
author:
  name: blackc0mb
  email: your-email@domain.com
description: blog under construction...
paginate: 5

minima:
  date_format: "%b %-d, %Y"

  social_links:
    twitter: cshkrs
    github: blackc0mb

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true

header_pages:
- about.md

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag