title: Tonatiuh Morales
author: 
  name: Tonatiuh Morales
  email: myemail@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Systems Engineer, web developer enthusiast, SAP Teach lead. Open to help & collaborate. This site was powered by github pages with jekyll minima theme.
  
show_excerpts: false # set to true to show excerpts on the homepage

minima:
  date_format: "%b %-d, %Y"

  social_links:
    twitter: cshkrs
    github:  blackc0mb

header_pages:
  - about.md  

theme: jekyll-theme-hacker

plugins:
 - jekyll-feed
 - jekyll-seo-tag