theme: jekyll-theme-slate

title: Tonatiuh Morales
description: blog under construction...
paginate: 5

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true

plugins:
  - jekyll-paginate
