  title: Tonatiuh Morales
author: 
  name: This site was powered by github pages with jekyll minima theme.
#  email: myemail@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Systems Engineer, web developer enthusiast, SAP Teach lead. Open to help & collaborate.  
  
show_excerpts: true # set to true to show excerpts on the homepage

minima:
  date_format: "%b %-d, %Y"  

  social_links:
    twitter: cshkrs
    github:  blackc0mb

header_pages:
  - about.md

minima:
  skin: dark

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
