theme: jekyll-theme-hacker

permalink: :title
relative_permalinks: true

title: Tonatiuh Morales
tagline: work in progress
description: blog under construction
paginate: 1

author:
  name: Tonatiuh Morales  

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true

plugins:
  - jekyll-paginate
