theme: jekyll-theme-hacker
title: Tonatiuh Morales
description: blog under construction
breadcrumbs: true
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

paginate: 5
plugins:
  - jekyll-paginate
