theme: jekyll-theme-hacker
title: Tonatiuh Morales
description: blog under construction

permalink: "/:title/"

highlighter: pygments

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true

paginate: 5
plugins:
  - jekyll-paginate
