theme: jekyll-theme-hacker

title: Tonatiuh Morales
description: blog under construction...
paginate: 5

author:
  name: Tonatiuh Morales  

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true

plugins:
  - jekyll-paginate
