theme: jekyll-theme-hacker
title: Tonatiuh Morales
description: blog under construction

paginate: 5
plugins:
  - jekyll-paginate
  
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
