title: Tonatiuh Morales
author:
  name: Tonatiuh Morales
  #email: your-email@domain.com
description:
  Cosas de hackers | Aprendiendo desarrollo web, pero si necesitas ayuda en plataformas SAP, adelante puedes preguntarme.
  ** Este sitio fue generado con Github Pages y usando el tema minima **

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: classic
  timezone: America/Mexico_City

  # generate social links in footer
  social_links:
    twitter: cshkrs
    github:  blackc0mb

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
